name: Build

on:
  workflow_dispatch:
  pull_request:
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '../../keymap-drawer/**'
      - '.github/workflows/draw-keymap.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/checkout@v3
        with:
          repository: bryanforbes/zmk
          ref: eb1b1d341f7f0a2bb40b30575f0d48bb95c48794 # bryanforbes branch
          path: src
          fetch-depth: 0
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-22.05
      - uses: cachix/cachix-action@v12
        with:
          name: moergo-glove80-zmk-dev
          skipPush: true
      - name: Generate firmware version
        id: firmware-version
        run: |
          FW_VERSION=$(date -u +"%y.%m.%d-%H%M")
          echo "version=${FW_VERSION}" >> "$GITHUB_OUTPUT"
      - name: Build Glove80 combined firmware
        run: nix-build config -o combined --argstr fwversion ${{ steps.firmware-version.outputs.version }}
      - name: Copy result out of nix store
        run: |
          cp combined/glove80.uf2 "glove80_${{ steps.firmware-version.outputs.version }}.uf2"
      - name: Glove80 Left Kconfig file
        if: ${{ !cancelled() }}
        run: |
          if [ -f "combined/zmk_glove80_lh.config" ]; then
            grep -v -e "^#" -e "^$" "combined/zmk_glove80_lh.config" | sort
          else
            echo "No Kconfig output"
          fi
      - name: Glove80 Right Kconfig file
        if: ${{ !cancelled() }}
        run: |
          if [ -f "combined/zmk_glove80_rh.config" ]; then
            grep -v -e "^#" -e "^$" "combined/zmk_glove80_rh.config" | sort
          else
            echo "No Kconfig output"
          fi
      - name: Glove80 Left Devicetree file
        if: ${{ !cancelled() }}
        run: |
          if [ -f "combined/zmk_glove80_lh.zephyr.dts" ]; then
            cat "combined/zmk_glove80_lh.zephyr.dts"
          elif [ -f "combined/zmk_glove80_lh.zephyr.dts.pre" ]; then
            cat "combined/zmk_glove80_lh.zephyr.dts.pre"
          else
            echo "No Devicetree output"
          fi
      - name: Glove80 Right Devicetree file
        if: ${{ !cancelled() }}
        run: |
          if [ -f "combined/zmk_glove80_rh.zephyr.dts" ]; then
            cat "combined/zmk_glove80_rh.zephyr.dts"
          elif [ -f "combined/zmk_glove80_rh.zephyr.dts.pre" ]; then
            cat "combined/zmk_glove80_rh.zephyr.dts.pre"
          else
            echo "No Devicetree output"
          fi
      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: glove80_${{ steps.firmware-version.outputs.version }}.uf2
          path: glove80_${{ steps.firmware-version.outputs.version }}.uf2
